// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFL1bn2j7vyol-occuQo6TDwtcCa9aQ3E',
    appId: '1:426337625591:web:5f0ed0affc8a9268e4baf2',
    messagingSenderId: '426337625591',
    projectId: 'pettycashapp-80f5e',
    authDomain: 'pettycashapp-80f5e.firebaseapp.com',
    storageBucket: 'pettycashapp-80f5e.firebasestorage.app',
    measurementId: 'G-RT2LCZWMN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuQa7DCq8dg-B4U86hr3G8a3fWPQgCGhI',
    appId: '1:426337625591:android:797b47f3154fecd7e4baf2',
    messagingSenderId: '426337625591',
    projectId: 'pettycashapp-80f5e',
    storageBucket: 'pettycashapp-80f5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkm_07NOkbg6n3XIwLhR1Qxizeefk1D8M',
    appId: '1:426337625591:ios:07238b82a2a142ffe4baf2',
    messagingSenderId: '426337625591',
    projectId: 'pettycashapp-80f5e',
    storageBucket: 'pettycashapp-80f5e.firebasestorage.app',
    iosBundleId: 'com.example.pettyCashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkm_07NOkbg6n3XIwLhR1Qxizeefk1D8M',
    appId: '1:426337625591:ios:07238b82a2a142ffe4baf2',
    messagingSenderId: '426337625591',
    projectId: 'pettycashapp-80f5e',
    storageBucket: 'pettycashapp-80f5e.firebasestorage.app',
    iosBundleId: 'com.example.pettyCashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFL1bn2j7vyol-occuQo6TDwtcCa9aQ3E',
    appId: '1:426337625591:web:9802a3c9e0400d23e4baf2',
    messagingSenderId: '426337625591',
    projectId: 'pettycashapp-80f5e',
    authDomain: 'pettycashapp-80f5e.firebaseapp.com',
    storageBucket: 'pettycashapp-80f5e.firebasestorage.app',
    measurementId: 'G-T6JC7YD79W',
  );
}
